version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: wizard_mongodb
    ports:
      - "27027:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=wizard
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123

volumes:
  mongodb_data: